[package]
name = "oid4vc"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of the OpenID4VC standards"
homepage = "https://www.impierce.com/"
keywords = ["openid4vc", "siopv2", "openid4vp", "openid4vci", "OpenID"]
license = "Apache-2.0"
repository = "https://github.com/impierce/openid4vc"

[workspace]
members = ["oid4vc-core", "oid4vci", "oid4vp", "siopv2", "oid4vc-manager"]

[workspace.package]
homepage = "https://www.impierce.com/"
license = "Apache-2.0"
repository = "https://github.com/impierce/openid4vc"

[workspace.dependencies]
chrono = "0.4"
# TODO: replace did-key
did-key = "0.2"
getset = "0.1"
http = "1.3.1"
identity_did = { git = "https://github.com/iotaledger/identity", tag = "v1.9.4-beta.1" }
identity_document = { git = "https://github.com/iotaledger/identity", tag = "v1.9.4-beta.1" }
identity_ecdsa_verifier = { git = "https://github.com/iotaledger/identity", tag = "v1.9.4-beta.1" }
identity_eddsa_verifier = { git = "https://github.com/iotaledger/identity", tag = "v1.9.4-beta.1" }
identity_credential = { git = "https://github.com/iotaledger/identity", tag = "v1.9.4-beta.1", default-features = false, features = [
    "validator",
    "credential",
    "presentation",
    "sd-jwt-vc",
] }
identity_jose = { git = "https://github.com/iotaledger/identity", tag = "v1.9.4-beta.1" }
identity_verification = { git = "https://github.com/iotaledger/identity", tag = "v1.9.4-beta.1" }
is_empty = "0.2"
jsonwebtoken = "9.3"
monostate = "0.1"
nutype = { version = "0.6", features = ["serde"] }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
reqwest-middleware = "0.2"
reqwest-retry = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
serde_with = "3.0"
tokio = { version = "1.46", features = ["rt", "macros", "rt-multi-thread"] }
thiserror = "1.0"
url = { version = "2", features = ["serde"] }

[dependencies]
oid4vc-core = { path = "oid4vc-core" }
oid4vci = { path = "oid4vci" }
oid4vp = { path = "oid4vp" }
siopv2 = { path = "siopv2" }
oid4vc-manager = { path = "oid4vc-manager" }

[patch.crates-io]
# We need this patch because it makes the `Hasher` trait `Send` and `Sync`. See: https://github.com/iotaledger/sd-jwt-payload/compare/main...impierce:sd-jwt-payload:fix/hasher-send-sync
sd-jwt = { git = "https://github.com/impierce/sd-jwt-payload", rev = "f28789a", package = "sd-jwt-payload" }
