name: 'Feature Request'
description: "Request a feature or provide a suggestion"
title: "[Request] "
labels: ["Request"]
body:
  - type: markdown
    attributes: 
      value: |
        You are requesting a feature or suggesting something to the maintainers.
  - type: textarea
    id: description
    attributes: 
      label: Description
      description: Briefly describe the feature that you are requesting.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes: 
      label: Motivation
      description: Explain why this feature is needed.
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Write a list of what you want this feature to do. 
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: openqs
    attributes: 
      label: Open Questions
      description: Use this section to ask any questions that are related to the feature.
    validations:
      required: false
  - type: dropdown
    id: doit
    attributes: 
      label: Are you planning to contribute this in a PR?
      options:
        - "Yes"
        - "No"
    validations:
      required: true