[package]
name = "oid4vp"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of the OpenID Connect OpenID for Verifiable Presentations standard"
homepage.workspace = true
keywords = ["oid4vc", "openid4vc", "oid4vp", "OpenID"]
license.workspace = true
repository.workspace = true

[dependencies]
oid4vc-core = { path = "../oid4vc-core" }
oid4vci = { path = "../oid4vci" }

anyhow = "1.0"
chrono.workspace = true
futures = "0.3"
getset.workspace = true
identity_core = { git = "https://github.com/iotaledger/identity", tag = "v1.9.1-beta.1" }
identity_credential.workspace = true
identity_did.workspace = true
identity_document.workspace = true
identity_jose.workspace = true
identity_verification.workspace = true
is_empty.workspace = true
jsonwebtoken.workspace = true
lazy_static = "1.4.0"
monostate.workspace = true
nutype.workspace = true
oauth_tsl = { git = "https://github.com/impierce/oauth-token-status-list", rev = "df371b9" }
reqwest.workspace = true
reqwest-middleware.workspace = true
reqwest-retry.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
oid4vc-core = { path = "../oid4vc-core", features = ["test-utils"] }
wiremock = "0.5"
