[package]
name = "siopv2"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
keywords = ["oid4vc", "openid4vc", "siopv2", "OpenID Connect"]
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1.26.0", features = ["rt", "macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_with = "2.3"
anyhow = "1.0.70"
chrono = "0.4.24"
getset = "0.1.2"
jsonwebtoken = "8.2.0"
jwt-simple = "0.11"
reqwest = { version = "0.11.14", default-features = false, features = ["json", "rustls-tls"] }
base64-url = "2.0.0"
async-trait = "0.1.68"
did_url = "0.1.0"
url = { version = "2.3.1", features = ["serde"] }
is_empty = "0.2.0"
serde_urlencoded = "0.7.1"
derive_more = "0.99.16"
bimap = "0.6"

[dev-dependencies]
ed25519-dalek = "1.0.1"
rand = "0.7"
lazy_static = "1.4.0"
derivative = "2.2.0"
wiremock = "0.5.18"
